name: Trivy Scan

on:
  workflow_call:
    inputs:
      image-ref:
        description: Docker image ref to be scanned by Trivy
        required: false
        type: string

jobs:
  trivy-fs:
    name: Scan filesystem
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Scan filesystem
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          format: sarif
          output: trivy-results.sarif

      - name: Upload scan results
        uses: github/codeql-action/upload-sarif@v3.26.6
        if: cancelled() == false
        with:
          sarif_file: trivy-results.sarif

  trivy-image:
    name: Scan image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Scan image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ inputs.image-ref }}
          format: sarif
          output: trivy-results.sarif

      - name: Upload scan results
        uses: github/codeql-action/upload-sarif@v3.26.6
        if: cancelled() == false
        with:
          sarif_file: trivy-results.sarif
